### ISSUE TITLE
Dicer

### ISSUE THREAD

**Issue by thomaes8** [koajs/joi-router#134]
# npm audit report

dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
fix available via `npm audit fix --force`
Will install koa-joi-router@4.0.0, which is a breaking change
node_modules/dicer
  busboy  <=0.3.1
  Depends on vulnerable versions of dicer
  node_modules/busboy
    await-busboy  *
    Depends on vulnerable versions of busboy
    node_modules/await-busboy
      koa-joi-router  >=5.0.0
      Depends on vulnerable versions of await-busboy
      node_modules/koa-joi-router

4 high severity vulnerabilities

**Node.js version:**  18.7.

**OS version:** Windows 10

**Comment by 3imed-jaberi** [comment]
@thomaes8 thank you for your report, This is not an issue because we replace the `await-busboy` module with a modern one `@fastify/busboy`!

If you need this catch ASAP, I recommend you to use [`@koa-better-modules/joi-router`](https://www.npmjs.com/package/@koa-better-modules/joi-router) until I can publish the official release under `@koa/joi-router`.

> For more details, you can [check 👀](https://github.com/koajs/joi-router/pull/128#pullrequestreview-929704834)!
