### ISSUE TITLE
Why using old koa-router?

### ISSUE THREAD

**Issue by nooks** [koajs/joi-router#52]
[In this line](https://github.com/koajs/joi-router/blob/master/package.json#L44)

**Comment by ryankeener** [comment]
This is of interest to me as well because it's causing CI installation failures due to a defect in npm5: https://github.com/npm/npm/issues/16839

**Comment by Aurelsicoko** [comment]
@ryankeener I have the exact same issue... I can't understand why we have this old dependency.

**Comment by tangxinfa** [comment]
the same problem to me, v4.0.0 can't install because dependencies broken:
$ npm install koa-joi-router@v4.x
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout f0c60d374b5903f
npm ERR! error: pathspec 'f0c60d374b5903f' did not match any file(s) known to git.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-02T03_35_17_326Z-debug.log

**Comment by aheckmann** [comment]
Released 5.1.0 which now includes koa-router 7.3.0. 

We were previously using a forked version because a [params fix](https://github.com/aheckmann/koa-router/commit/19e60d915a948c93a728ecbd90b92060b1206f24) hadn't been merged/released in koa-router.

**Comment by Aurelsicoko** [comment]
Thank you @aheckmann!
